"""Workspace lifecycle (mock).

Real implementation would create isolated directories on the VPS, e.g.
    /workspaces/companies/<company-slug>/<project-slug>/
For MVP it returns the standard tree and mock metrics without touching disk.
"""
from __future__ import annotations

import re
from datetime import datetime, timezone

from api.config import settings

STANDARD_TREE = [
    {"path": "/src", "kind": "dir"},
    {"path": "/docs", "kind": "dir"},
    {"path": "/assets", "kind": "dir"},
    {"path": "/tests", "kind": "dir"},
    {"path": "/logs", "kind": "dir"},
    {"path": "/output", "kind": "dir"},
    {"path": "README.md", "kind": "file", "preview": "# Project\n\nGenerated by AI Agent Office."},
    {"path": "project.json", "kind": "file", "preview": '{\n  "name": "project"\n}'},
]


def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-") or "item"


class WorkspaceManager:
    def create_workspace(self, company_id: int, project_id: int, project_name: str) -> dict:
        # FUTURE: os.makedirs on the VPS + git init + template copy.
        path = f"{settings.workspaces_root}/company-{company_id}/{_slug(project_name)}"
        return {"path": path, "tree": STANDARD_TREE, "status": "created"}

    def read_logs(self, workspace_path: str) -> list[dict]:
        # FUTURE: tail real log files from the workspace /logs directory.
        now = datetime.now(timezone.utc).isoformat()
        return [
            {"ts": now, "level": "info", "line": f"workspace {workspace_path} ready"},
            {"ts": now, "level": "info", "line": "npm install (mock) completed in 4.2s"},
            {"ts": now, "level": "info", "line": "build (mock) succeeded"},
            {"ts": now, "level": "warn", "line": "2 lint warnings (mock)"},
        ]

    def status(self, workspace) -> dict:
        # FUTURE: read real cgroup / docker stats.
        if workspace is None:
            return {"status": "not_provisioned", "cpu_percent": 0, "memory_mb": 0, "disk_mb": 0}
        return {
            "status": workspace.status,
            "cpu_percent": workspace.cpu_percent,
            "memory_mb": workspace.memory_mb,
            "disk_mb": workspace.disk_mb,
        }
