import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";

/**
 * WP-002R correction cycle 1 — worker identity consistency.
 *
 * Defect: each worker state was generated by an independent text-to-image call,
 * so all six invented a different robot. The spec requires ONE character in six
 * states. Fix: keep `idle` as the identity anchor and derive the other five via
 * the image-edit endpoint, which conditions on the anchor image.
 */
const REPO = path.resolve(process.cwd(), "..", "..");
const STAGE = path.join(REPO, "artifacts/WP-002R/staging");
const TOOL = path.join(REPO, "tools/asset_pipeline/imagetool.py");
const toPosix = (p: string) => p.split(path.sep).join("/");

const STATES: [string, string][] = [
  ["working", "actively working: leaning forward slightly with both arms raised as if typing, bright BLUE visor glow, a few small motion sparks"],
  ["thinking", "thinking and reasoning: one hand raised near the side of the head, AMBER visor glow, three small floating thought dots above the head"],
  ["waiting-approval", "waiting for human approval: standing patiently holding up a blank rectangular document panel with both hands, PURPLE visor glow"],
  ["error", "error state: slumped dejected posture, RED visor glow, a small warning triangle symbol floating above the head, no letters"],
  ["offline", "powered down: slouched inactive posture, visor completely dark and unlit, whole body desaturated grey"],
];

function tool(args: string[]) {
  try {
    const out = execFileSync("python", [TOOL, ...args], { encoding: "utf8", cwd: REPO, maxBuffer: 32 << 20 });
    return JSON.parse(out.trim().split("\n").filter(Boolean).pop() ?? "{}");
  } catch (e) { return { ok: false, error: (e as Error).message.slice(0, 200) }; }
}

(async () => {
  const anchorWebp = path.join(STAGE, "idle.webp");
  const anchorPng = path.join(STAGE, "_anchor-idle.png");
  // edits endpoint needs PNG with alpha
  execFileSync("python", ["-c",
    `from PIL import Image; Image.open(r"${anchorWebp}").convert("RGBA").save(r"${anchorPng}")`],
    { cwd: REPO });
  console.log("anchor: idle.webp -> PNG ok");

  const manifestPath = path.join(STAGE, "generation-manifest.json");
  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8")) as Record<string, unknown>[];

  for (const [slug, treatment] of STATES) {
    const prompt = [
      "Keep EXACTLY the same robot character as the reference image: identical body design, identical colours,",
      "identical proportions, identical pixel-art style, identical size and camera angle.",
      `Change ONLY the pose and the visor colour to convey this state — ${treatment}.`,
      "Full body head to feet, both feet on the same ground line at the bottom of the frame.",
      "Fully transparent background. NO furniture, NO background scenery, NO humans, NO text, NO logos.",
    ].join(" ");

    let ok = false, err = "";
    for (let attempt = 1; attempt <= 3 && !ok; attempt++) {
      const fd = new FormData();
      fd.append("model", "gpt-image-1");
      fd.append("image", new Blob([fs.readFileSync(anchorPng)], { type: "image/png" }), "idle.png");
      fd.append("prompt", prompt);
      fd.append("size", "1024x1536");
      fd.append("background", "transparent");
      const res = await fetch("https://api.openai.com/v1/images/edits", {
        method: "POST", headers: { Authorization: `Bearer ${process.env.OPENAI_API_KEY}` }, body: fd,
      });
      if (!res.ok) { err = `HTTP ${res.status}: ${(await res.text()).slice(0, 160)}`; console.log(`  .. ${slug} a${attempt}: ${err}`); continue; }
      const j = await res.json() as { data: { b64_json?: string }[] };
      const b64 = j.data?.[0]?.b64_json;
      if (!b64) { err = "no payload"; continue; }

      const raw = path.join(STAGE, `${slug}-edit.png`);
      fs.writeFileSync(raw, Buffer.from(b64, "base64"));
      const rel = toPosix(path.relative(REPO, path.join(STAGE, `${slug}.webp`)));
      const norm = tool(["normalize", "--src", toPosix(raw), "--out", rel, "--width", "512", "--height", "768", "--fit", "contain", "--alpha"]);
      if (!norm.ok) { err = String(norm.error); continue; }
      const val = tool(["validate", "--path", rel, "--width", "512", "--height", "768", "--alpha"]);
      if (!val.ok) { err = JSON.stringify(val.issues ?? val.error); continue; }

      const abs = path.join(STAGE, `${slug}.webp`);
      const sha = createHash("sha256").update(fs.readFileSync(abs)).digest("hex");
      const i = manifest.findIndex((m) => m.assetKey === slug);
      if (i >= 0) manifest[i] = { ...manifest[i], sha256: sha, fileSizeBytes: fs.statSync(abs).size,
        derivedFrom: "idle", method: "images.edits", attempts: attempt, validation: "PASSED" };
      fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
      fs.rmSync(raw, { force: true });
      console.log(`OK  ${slug}  sha=${sha.slice(0, 12)} (derived from idle, attempt ${attempt})`);
      ok = true;
    }
    if (!ok) console.log(`FAIL ${slug}: ${err}`);
  }
  fs.rmSync(anchorPng, { force: true });
})();
